---
name: 'Terraform Plan/Apply'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install latest terraform version
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          # We do not want the terraform wrapper that is masking the terraform plan -detailed-exitcode.
          terraform_wrapper: false

      - name: Prepare ID token request
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: idtokenprep
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_ID_TOKEN_REQUEST_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())

      - name: Get ID token
        id: idtoken
        run: |
          IDTOKEN=$(curl -H "Authorization: Bearer ${{steps.idtokenprep.outputs.TOKEN}}" ${{steps.idtokenprep.outputs.IDTOKENURL}}  -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
          echo $IDTOKEN
          jwtd() {
              if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
              fi
          }
          jwtd $IDTOKEN
          echo "id_token=${IDTOKEN}" >> $GITHUB_OUTPUT

      # Exchange the OIDC token for a short-lived Zentral API token
      - name: Get Zentral API token
        id: ztlapitoken
        run: |
          API_TOKEN=$(curl -X POST -H 'Content-Type: application/json' -d "{\"jwt\": \"$ID_TOKEN\", \"name\": \"GitHub action\", \"validity\": 600}" https://$ZTL_FQDN/api/accounts/token_issuers/oidc/$ZTL_OIDC_API_TOKEN_ISSUER_ID/auth/ | jq -r .secret)
          echo "api_token=${API_TOKEN}" >> $GITHUB_OUTPUT
        env:
          ZTL_FQDN: ${{ vars.ZTL_FQDN }}
          ZTL_OIDC_API_TOKEN_ISSUER_ID: ${{ vars.ZTL_OIDC_API_TOKEN_ISSUER_ID }}
          ID_TOKEN: ${{ steps.idtoken.outputs.id_token }}

      # Initialize a new or existing Terraform working directory by creating initial files,
      # loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: >-
          terraform init
          -backend-config="username=$ZTL_USERNAME"
          -backend-config="password=$ZTL_API_TOKEN"
        env:
          ZTL_USERNAME: ${{ vars.ZTL_USERNAME }}
          ZTL_API_TOKEN: ${{ steps.ztlapitoken.outputs.api_token }}

      # Checks that all Terraform configuration files adhere to a canonical format
      # Will fail the build if not
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi
        env:
          TF_VAR_fqdn: ${{ vars.ZTL_FQDN }}
          TF_VAR_api_token: ${{ steps.ztlapitoken.outputs.api_token }}
          TF_VAR_chrome_enrollment_token: ${{ secrets.CHROME_ENROLLMENT_TOKEN }}
          TF_VAR_okta_scep_issuer_password: ${{ secrets.OKTA_SCEP_ISSUER_PASSWORD }}
          TF_VAR_okta_desktop_password_sync_client_id: ${{ secrets.OKTA_DESKTOP_PASSWORD_SYNC_CLIENT_ID }}
          TF_VAR_munki_repo_secret_access_key: ${{ secrets.MUNKI_REPO_SECRET_ACCESS_KEY }}
          TF_VAR_slack_incoming_webhook_url: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          TF_VAR_http_post_api_endpoint_url: ${{ secrets.HTTP_POST_API_ENDPOINT_URL }}
          TF_VAR_http_post_api_bearer_token: ${{ secrets.HTTP_POST_API_BEARER_TOKEN }}
          TF_VAR_wifi_ham_ssid: ${{ vars.WIFI_HAM_SSID }}
          TF_VAR_wifi_ham_pwd: ${{ secrets.WIFI_HAM_PWD }}
          TF_VAR_wifi_ldn_ssid: ${{ vars.WIFI_LDN_SSID }}
          TF_VAR_wifi_ldn_pwd: ${{ secrets.WIFI_LDN_PWD }}
          TF_VAR_macos_27_beta_token: ${{ secrets.MACOS_27_BETA_TOKEN }}
          TF_VAR_turbo_enrollment_secret: ${{ secrets.TURBO_ENROLLMENT_SECRET }}

      # Save plan to artifacts
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tfplan
          path: ./tfplan

      # Create string output of Terraform Plan
      - name: Create String Output
        id: tf-plan-string
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
          NEWLINE=$'\n'
          [ ${#TERRAFORM_PLAN} -gt 32768 ] && TERRAFORM_PLAN="${TERRAFORM_PLAN:0:32750}$NEWLINE--- TRUNCATED ---"

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # Publish Terraform Plan as task summary
      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      # If this is a PR post the changes
      - name: Push Terraform Output to PR
        if: github.ref != 'refs/heads/main'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })

  terraform-apply:
    name: 'Terraform Apply'
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
    runs-on: ubuntu-latest
    needs: [terraform-plan]

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install latest terraform version
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          # We do not want the terraform wrapper. Too much magic.
          terraform_wrapper: false

      - name: Prepare ID token request
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: idtokenprep
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_ID_TOKEN_REQUEST_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())

      - name: Get ID token
        id: idtoken
        run: |
          IDTOKEN=$(curl -H "Authorization: Bearer ${{steps.idtokenprep.outputs.TOKEN}}" ${{steps.idtokenprep.outputs.IDTOKENURL}}  -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
          echo $IDTOKEN
          jwtd() {
              if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
              fi
          }
          jwtd $IDTOKEN
          echo "id_token=${IDTOKEN}" >> $GITHUB_OUTPUT

      # Exchange the OIDC token for a short-lived Zentral API token
      - name: Get Zentral API token
        id: ztlapitoken
        run: |
          API_TOKEN=$(curl -X POST -H 'Content-Type: application/json' -d "{\"jwt\": \"$ID_TOKEN\", \"name\": \"GitHub action\", \"validity\": 600}" https://$ZTL_FQDN/api/accounts/token_issuers/oidc/$ZTL_OIDC_API_TOKEN_ISSUER_ID/auth/ | jq -r .secret)
          echo "api_token=${API_TOKEN}" >> $GITHUB_OUTPUT
        env:
          ZTL_FQDN: ${{ vars.ZTL_FQDN }}
          ZTL_OIDC_API_TOKEN_ISSUER_ID: ${{ vars.ZTL_OIDC_API_TOKEN_ISSUER_ID }}
          ID_TOKEN: ${{ steps.idtoken.outputs.id_token }}

      # Initialize a new or existing Terraform working directory by creating initial files,
      # loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: >-
          terraform init
          -backend-config="username=$ZTL_USERNAME"
          -backend-config="password=$ZTL_API_TOKEN"
        env:
          ZTL_USERNAME: ${{ vars.ZTL_USERNAME }}
          ZTL_API_TOKEN: ${{ steps.ztlapitoken.outputs.api_token }}

      # Download saved plan from artifacts
      - name: Download Terraform Plan
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tfplan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
